### ISSUE TITLE
64 bit version 

### ISSUE THREAD

**Issue by mksharmamk** [dmitriychunikhin/pdfium-vfp#2]
Please required 64bit version of this nice tool for use with VFP Advanced 64bit

Warm regards 
Mk

**Comment by dmitriychunikhin** [comment]
I've added VFPA x64 support for pdf viewer (but not for pdfiumreport yet) 
Check it out
git clone https://github.com/dmitriychunikhin/pdfium-vfp
and
git switch 1.5

2 new files was added: Source/pdfium64.dll and Source/pdfium-vfp64.dll, I have to copy them to your project folder before start

I've tested changes on VFPA 10.0 x64

**Comment by mksharmamk** [comment]
Thank you,
I think we also need 64bit libhpdf.dll ?

Warm regards,
mk.

**Comment by dmitriychunikhin** [comment]
I'll add libhpdf64.dll today. You need it only if you use pdfiumreport.app

**Comment by mksharmamk** [comment]
Thank you,
Yes when vfpa report to pdf.

Warm regards,
mk.

**Comment by dmitriychunikhin** [comment]
Just have added libpng64.dll. 
Source/pdfium-vfp.vcx,pdfum-vfp.vct, Sample/sample.scx, sample.sct have been changed also.   
These changes are still in the branch 1.5

Sample reports work fine in  VFPA 10.0 x64
Please, check it out in your environment and give a feedback

**Comment by mksharmamk** [comment]
Thank you,
tested in VFPA 10.1 64bit and VFPA 10.2 64bit 
Working perfectly in above both VFPA versions :)

Warm regards,
mk.
